print("Welcome to Code Lab 1")
print("Self Introduction")
print("Hy my name is abiha asad")
print("i was born in UAE,Ajman.")
print("i graduated from pakistan islamia higher secondary school")
print("currently i am doing BSc in creative computing from university of bath spa")
print("""i am 19 years old""")
print("""i am a atheletic person""")
print("i love singing ,coloring")
print("i love to watch Tv")